#!/bin/bash
# Bump the build stamp shown in the bottom-left of every page.
# Auto-runs from the pre-commit hook so each commit gets a fresh number.
set -e
cd "$(dirname "$0")"
# Counter from total commits + 1 (this commit isn't recorded yet at pre-commit time)
BUILD=$(( $(git rev-list --count HEAD 2>/dev/null || echo 0) + 1 ))
HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "dev")
DATE=$(date -u +"%Y-%m-%d %H:%M UTC")
cat > shared/version.js <<EOF
// Auto-generated by bump-version.sh — do not edit by hand.
window.__BUILD__ = {
  build: '$BUILD',
  hash: '$HASH',
  date: '$DATE'
};
EOF
echo "→ shared/version.js: build #$BUILD ($HASH)"
